lib/aliyar_web/router.ex
defmodule AliyarWeb.Router do
  use AliyarWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, html: {AliyarWeb.Layouts, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Other scopes may use custom stacks.
  # scope "/api", AliyarWeb do
  #   pipe_through :api
  # end

  # Enable LiveDashboard and Swoosh mailbox preview in development
  if Application.compile_env(:aliyar, :dev_routes) do
    # If you want to use the LiveDashboard in production, you should put
    # it behind authentication and allow only admins to access it.
    # If your application does not have an admins-only section yet,
    # you can use Plug.BasicAuth to set up some basic authentication
    # as long as you are also using SSL (which you should anyway).
    import Phoenix.LiveDashboard.Router

    scope "/dev" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: AliyarWeb.Telemetry
      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end

    scope "/", AliyarWeb do
      pipe_through :browser

      get "/", AliyarController, :index

      get "/admin", AdminController, :login_admin_submit
      get "/admin/login", AdminController, :login_form
      get "/admin/exchanges", AdminController, :exchanges_list
      get "/admin/exchanges/update", AdminController, :exchanges_update

    end
  end

end

lib/aliyar_web/controllers/admin_controller.ex
defmodule AliyarWeb.AdminController do
  use AliyarWeb, :controller

  @doc """
  GET /admin/login
  Форма авторизации админа.
  """
  def login_form(conn, _params) do
    IO.inspect("TUT")
    conn
    |> render(:login_form)
  end

  @doc """
  POST /admin/login
  Проверка вводимых данных при авторизации админа.
  """
  def login_admin_submit(conn, params) do
    IO.inspect(params)

    opts = %{
      login: params["login"],
      password: :crypto.hash(:sha256, params["password"]) |> Base.encode16()
    }

    case Aliyar.Context.Users.do_get(opts) do
      {:ok, admin} ->
        conn
        |> put_session(:admin, %{id: admin.id, login: admin.login})
        |> put_flash(:info, "Добро пожаловать #{admin.login}")
        |> redirect(to: "/admin/exchanges")

      {:error, :not_found} ->
        conn
        |> put_flash(:error, "Невеный логин или пароль")
        |> redirect(to: "/admin/login")
    end
  end

  def exchanges_list(conn, _params) do
    all_exchanges =
      Aliyar.Context.Exchanges.all()
      |> Enum.map(& Map.from_struct(&1))

    conn
    |> render(:exchanges_list, exchanges: all_exchanges)
  end

  # @doc """
  # GET /admin/logout
  # Выход из личного кабинета админа.
  # """
  # def admin_logout(conn, _params) do
  #   conn
  #   |> delete_session(:admin)
  #   |> redirect(to: "/admin/login")
  # end
end

lib/aliyar_web/controllers/admin_html.ex
defmodule AliyarWeb.AdminHTML do
  use AliyarWeb, :html
  # import Phoenix.HTML.Form

  embed_templates "admin_html/*"
end

lib/aliyar_web/controllers/aliyar_controller.ex
defmodule AliyarWeb.AliyarController do
  use AliyarWeb, :controller

  def index(conn, _params) do
    conn
    |> put_layout(html: :page)
    |> render(:index)
  end

end

lib/aliyar_web/controllers/aliyar_html.ex
defmodule AliyarWeb.AliyarHTML do
  use AliyarWeb, :html

  # def index(assigns) do
  #   ~H"""
  #   Hello!
  #   """
  # end

  embed_templates "aliyar_html/*"
end

lib/aliyar_web/controllers/error_html.ex
defmodule AliyarWeb.ErrorHTML do
  use AliyarWeb, :html

  # If you want to customize your error pages,
  # uncomment the embed_templates/1 call below
  # and add pages to the error directory:
  #
  #   * lib/aliyar_web/controllers/error_html/404.html.heex
  #   * lib/aliyar_web/controllers/error_html/500.html.heex
  #
  # embed_templates "error_html/*"

  # The default is to render a plain text page based on
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def render(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/aliyar_web/controllers/page_html.ex
defmodule AliyarWeb.PageHTML do
  use AliyarWeb, :html

  embed_templates "page_html/*"
end

lib/aliyar_web/controllers/admin_html/exchanges_list.html.heex
<!-- <div class="margin_content">
    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
        <%= form_for @conn.params, Routes.admin_path(@conn, :exchanges_update), fn f -> %>
            <div class="flex gap-4">
                <button id="submit-btn" class="btn_save flex items-center justify-center" type="submit">
                    <span class="material-symbols-outlined" style="color: #fff; font-weight: 500; font-size: 20px;">
                        save
                    </span>
                    <%= gettext("Сохранить изменения") %>
                </button>
                <a href="/worker/course" class="btn_cancel flex items-center justify-center" type="submit">
                    <span class="material-symbols-outlined" style="color: #111111; font-weight: 500; font-size: 20px;">
                        cancel
                    </span>
                    <%= gettext("Отменить изменения") %>
                </a>
                <table class="w-full text-sm 2xl:text-xs text-left text-gray-500 table_sort">
                    <thead class="text-xs text-gray-700 uppercase bg-white">
                        <tr>
                            <th scope="col" class="p-6 2xl:p-4 border-b-2 border-gray-200 mob:hidden">
                                <%= gettext("Валюта") %>
                            </th>
                            <th scope="col" class="p-6 2xl:p-4 border-b-2 border-x-2 border-gray-200">
                                <%= gettext("Цена покупки") %>
                            </th>
                            <th scope="col" class="p-6 2xl:p-4 border-b-2 border-x-2 border-gray-200">
                                <%= gettext("Цена продажи") %>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <%= for item <- @exchanges do %>
                            <tr class="bg-white td-item">
                                <td class="px-6 py-4 border-t-2 mob:hidden">
                                    <%= item.currency %>
                                </td>
                                <td class="px-6 py-4 border-t-2 border-x-2 border-gray-200">
                                    <%= number_input f, :purchase, class: "input_full md:!w-32 number purchase" , value:
                                        item.purchase, step: "any" %>
                                </td>
                                <td class="px-6 py-4 border-x-2 border-t-2">
                                    <%= number_input f, :sale, class: "input_full md:!w-32 number sale" , value:
                                        item.sale, step: "any" %>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        <% end %>
    </div>
</div>




<script>
    const numberInputs = document.querySelectorAll('.number');
    numberInputs.forEach(function (e) {
        let previousValue = '';
        e.addEventListener('input', () => {
            const currentValue = e.value;
            if (currentValue === '' || currentValue === '.' || currentValue === ',' || /^\d+(,\d{0,3})?(\.\d{0,3})?$/.test(currentValue)) {
                previousValue = currentValue;
            }
            else {
                e.value = previousValue;
            }
        });
    });


    const elementTd = Array.from(document.querySelectorAll(".td-item"));

    elementTd.forEach((el) => {
        const valueForPurchaseInput = el.querySelector(".purchase");
        const valueForSaleInput = el.querySelector(".sale");

        differenceInputs(valueForSaleInput, valueForPurchaseInput);
    });

    const buttonSubmit = document.querySelector("#submit-btn");
    let inputsArray = Array.from(document.querySelectorAll('input'));
    let isValid = true;

    function differenceInputs(oneInput, twoInput) {
        oneInput.addEventListener("input", handleInput);
        twoInput.addEventListener("input", handleInput);

        function handleInput() {
            let valueOne = parseFloat(oneInput.value.replace(/\s/, "").replace(",", ".") || 0);
            let valueTwo = parseFloat(twoInput.value.replace(/\s/, "").replace(",", ".") || 0);

            let isOneInputError = false;
            let isTwoInputError = false;

            if (isNaN(valueOne) || !(/^\d+(,\d{0,3})?(\.\d{0,3})?$/.test(oneInput.value))) {
                oneInput.style.border = "1px solid red";
                isOneInputError = true;
            } else {
                oneInput.style.border = "";
            }

            if (isNaN(valueTwo) || !(/^\d+(,\d{0,3})?(\.\d{0,3})?$/.test(twoInput.value))) {
                twoInput.style.border = "1px solid red";
                isTwoInputError = true;
            } else {
                twoInput.style.border = "";
            }

            if (isOneInputError || isTwoInputError) {
                buttonSubmit.disabled = true;
                return;
            }

            const lastCharIndexOne = oneInput.value.length - 1;
            const isLastCharDotOne = oneInput.value[lastCharIndexOne] === "." || oneInput.value[lastCharIndexOne] === ",";

            if (isLastCharDotOne && lastCharIndexOne > 0) {
                oneInput.style.border = "1px solid red";
                buttonSubmit.disabled = true;
                return;
            }

            const lastCharIndexTwo = twoInput.value.length - 1;
            const isLastCharDotTwo = twoInput.value[lastCharIndexTwo] === "." || twoInput.value[lastCharIndexTwo] === ",";

            if (isLastCharDotTwo && lastCharIndexTwo > 0) {
                twoInput.style.border = "1px solid red";
                buttonSubmit.disabled = true;
                return;
            }

            if (valueOne < valueTwo) {
                twoInput.style.border = "1px solid red";
                buttonSubmit.disabled = true;
            } else {
                oneInput.style.border = "";
                twoInput.style.border = "";
                inputsArray = Array.from(document.querySelectorAll('input'));
                const borderColorsArray = inputsArray.map(input => input.style.borderColor === "" ? true : false);
                isValid = borderColorsArray.every(value => value === true);

                if (isValid) {
                    oneInput.style.border = "";
                    twoInput.style.border = "";
                    buttonSubmit.disabled = false;
                }
            }
        }
    }
</script> -->

lib/aliyar_web/controllers/admin_html/login_form.html.heex
<div class="login-container">
    <div class="round">
      <!-- <a href="/" class=" w-80"><img src="/images/logo-line.png" class="logo-login" alt=""></a> -->
      <!-- <div class="login-title">Авторизация в системе администратора</div> -->
      <form action="/admin" method="get">

        <!-- <label for="fname">Логин</label><br>
        <input type="text" id="fname" name="fname"><br>
        <label for="lname">Пароль:</label><br>
        <input type="text" id="lname" name="lname">

        <div class="favorite styled" style="background-color:#f1f1f1">
          <button type="button" class="cancelbtn">Войти</button>
          <span class="password"><a href="/admin"></a></span>
        </div>

        <button type="submit">Войти</button> -->


        <!-- <label for="fname" class="favorite styled">Войти<a href="/admin"></a></label><br>
        <input type="button" id="entrance"> -->
        

        <div class="imgcontainer">
          <img src="img_avatar2.png" alt="Avatar" class="avatar">
        </div>
      
        <div class="container">
          <label for="login"><b>Username</b></label>
          <input type="text" placeholder="Enter Username" name="login" required>
          
          <label for="password"><b>Password</b></label>
          <input type="password" placeholder="Enter Password" name="password" required>
      
          <button type="submit">Login</button>
          <label>
            <input type="checkbox" checked="checked" name="remember"> Remember me
          </label>
        </div>


      </form>
    </div>
</div>


<style>
  /* Bordered form */
  form {
      border: 3px solid #f1f1f1;
  }

  /* Full-width inputs */
  input[type=text], input[type=password] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
  }

  /* Set a style for all buttons */
  button {
      background-color: #4CAF50;
      color: white;
      padding: 14px 20px;
      margin: 8px 0;
      border: none;
      cursor: pointer;
      width: 100%;
  }

  /* Add a hover effect for buttons */
  button:hover {
      opacity: 0.8;
  }

  /* Extra style for the cancel button (red) */
  .cancelbtn {
      width: auto;
      padding: 10px 18px;
      background-color: #f44336;
  }

  /* Center the avatar image inside this container */
  .imgcontainer {
      text-align: center;
      margin: 24px 0 12px 0;
  }

  /* Avatar image */
  img.avatar {
      width: 40%;
      border-radius: 50%;
  }

  /* Add padding to containers */
  .container {
      padding: 16px;
  }

  /* The "Forgot password" text */
  span.password {
      float: right;
      padding-top: 16px;
  }

  /* Change styles for span and cancel button on extra small screens */
  @media screen and (max-width: 300px) {
      span.password {
          display: block;
          float: none;
      }
      .cancelbtn {
          width: 100%;
      }
  }






  /* .login-container {
    left: 0;
    top: 0;
    position: absolute;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    width: 100vw;
    background-color: #3689ce;
  }

  .round {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    background-color: #fff;
    border-radius: 100%;
    min-width: 600px;
    min-height: 600px;
    z-index: 1 !important;
  }

  .form-group {
    display: flex;
    justify-content: space-between;
    padding-bottom: 20px;
    font-family: 'Montserrat', sans-serif;
  }

  .form-group label {
    margin-right: 40px;
    display: flex;
    justify-content: start;
  }

  .login-title {
    color: #7e7e7e;
    text-transform: uppercase;
    font-weight: 500;
    padding: 0 0 20px 0;
  }

  .input-login {
    height: 56px;
    margin-left: -5px;
    padding: 0 10px;
    background-color: #f3f3f3;
    border: none;
    outline: none;
    border-radius: 10px;
  }

  .input-login:focus {
    outline: none;
    border: none;
  }

  .btn-login {
    color: #7e7e7e;
    text-transform: uppercase;
    font-weight: 700;
    margin: 0 auto;
    color: #fff;
    border: none;
    width: 100%;
    background-color: #3689ce;
    padding: 8px 25px;
    border-radius: 10px;
  }

  .styled {
  border: 0;
  line-height: 2.5;
  padding: 0 20px;
  font-size: 1rem;
  text-align: center;
  color: #fff;
  text-shadow: 1px 1px 1px #000;
  border-radius: 10px;
  background-color: rgb(10, 3, 14);
  background-image: linear-gradient(to top left, rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2) 30%, rgba(0, 0, 0, 0));
  box-shadow:
    inset 2px 2px 3px rgba(255, 255, 255, 0.6),
    inset -2px -2px 3px rgba(0, 0, 0, 0.6);
  }

  .styled:hover {
    background-color: rgb(51, 45, 45);
  }

  .styled:active {
    box-shadow:
      inset -2px -2px 3px rgba(255, 255, 255, 0.6),
      inset 2px 2px 3px rgba(0, 0, 0, 0.6);
  } */
</style>